# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import perfil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(default='position', max_length=50)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(default=perfil.models.unique_rand, error_messages={'unique': 'Ya existe un perfil con este Alias'}, max_length=30, unique=True)),
                ('reputation', models.IntegerField(blank=True, default=0)),
                ('img', models.FileField(blank=True, default='RDdefault.png', null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
