# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20180925_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userslist',
            old_name='owner_type',
            new_name='type',
        ),
    ]
