# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumen', '0001_initial'),
        ('debate', '0003_privatemembers_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.IntegerField(default=0)),
                ('type', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Argumento',
            new_name='Argument',
        ),
        migrations.AddField(
            model_name='report',
            name='argument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Argument'),
        ),
        migrations.AddField(
            model_name='report',
            name='counterarg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Counterargument'),
        ),
        migrations.AddField(
            model_name='report',
            name='debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate'),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
