# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20180928_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
