# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='img',
            field=models.FileField(blank=True, default='RDdefault.png', null=True, upload_to=b''),
        ),
    ]
