# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0002_debate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
