# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0003_auto_20181025_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='participation_type',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
